# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

for file in $HOME/dotfiles/.{aliases}; do
	[ -r "$file" ] && source "$file"
done
unset file

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="steeef"

# Example aliases
 alias ack="nocorrect ack"
 alias yo="nocorrect yo"
 alias irb="irb --readline -r irb/completion"
 alias zshconfig="vim ~/.zshrc"
 alias tmuxconfig="vim ~/.tmux.conf"
 alias ohmyzsh="vim ~/.oh-my-zsh"
 alias vimrc="vim ~/.vimrc"
 alias hosts="vim /etc/hosts"
 alias cl="clear"
 alias redis="redis-server /usr/local/etc/redis.conf"
 alias mysql-server="mysql.server start"
 alias composer='nocorrect composer'
 alias server='python -m SimpleHTTPServer 8888'
 alias bower='noglob bower'
 alias claer='clear'

#Puppet Alias
 alias puppet="nocorrect puppet"
 alias ppmodin="puppet module install --modulepath=./modules --module_repository=http://forge.puppetlabs.com --force"
 
# Apache Vhost config
alias vhost="sudo vim /etc/apache2/extra/httpd-vhosts.conf"

# /etc/hosts config
alias hosts="sudo vim /etc/hosts"


# IP addresses
 alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
 alias localip="ipconfig getifaddr en1"
 alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"

 # Enhanced WHOIS lookups
 alias whois="whois -h whois-servers.net"

 # Flush Directory Service cache
 alias flush="dscacheutil -flushcache"

# # View HTTP traffic
 alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
 alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# `cat` with beautiful colors. requires Pygments installed.
# 							   sudo easy_install Pygments
alias c='pygmentize -O style=monokai -f console256 -g'

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
#
#export PATH=/opt/local/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/usr/X11/bin:/usr/local/mysql/bin
#export PATH="$HOME/.rbenv/bin:$PATH"
#eval "$(rbenv init - zsh)"
#. ~/.nvm/nvm.sh
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

. `brew --prefix`/etc/profile.d/z.sh
#export PATH="/usr/bin:$PATH"
export PATH="/usr/local/php5/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH:/usr/local/go/bin"
eval "$(rbenv init - zsh)"
export PATH="/usr/local/bin:$PATH"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

#### GoPath
export GOPATH=/Users/lionel/go
